# Generated by Django 5.1 on 2024-08-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_remove_campaignnews_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='categories',
            field=models.ManyToManyField(to='campaigns.campaigncategory'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=models.ManyToManyField(to='campaigns.campaigntag'),
        ),
        migrations.AddField(
            model_name='campaignteammember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='team_members/'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('uzs', 'UZS')], max_length=10),
        ),
        migrations.AlterField(
            model_name='campaignrating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')]),
        ),
    ]
