# Generated by Django 5.1 on 2024-08-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='campaigncategory',
            options={'verbose_name_plural': 'Campaign Categories'},
        ),
        migrations.AlterModelOptions(
            name='campaignmedia',
            options={'verbose_name_plural': 'Campaign Media'},
        ),
        migrations.AlterModelOptions(
            name='campaignnews',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Campaign News'},
        ),
        migrations.AlterModelOptions(
            name='campaignnewsmedia',
            options={'verbose_name_plural': 'Campaign News Media'},
        ),
        migrations.AlterModelOptions(
            name='campaignrating',
            options={'ordering': ['-rated_at'], 'verbose_name_plural': 'Campaign Ratings'},
        ),
        migrations.AlterModelOptions(
            name='campaigntag',
            options={'verbose_name_plural': 'Campaign Tags'},
        ),
        migrations.AlterModelOptions(
            name='campaignteammember',
            options={'verbose_name_plural': 'Campaign Team Members'},
        ),
        migrations.AlterModelOptions(
            name='campaignvisit',
            options={'ordering': ['-visited_at'], 'verbose_name_plural': 'Campaign Visits'},
        ),
        migrations.RenameField(
            model_name='campaignnews',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='campaignnews',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
