# Generated by Django 5.1 on 2024-08-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaignnews',
            name='media',
        ),
        migrations.AlterField(
            model_name='campaignnewsmedia',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
