# Generated by Django 5.1 on 2024-08-21 10:36

import apps.campaigns.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_campaign_categories_campaign_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmedia',
            name='file',
            field=models.FileField(upload_to=apps.campaigns.models.campaign_media_upload_path),
        ),
        migrations.AlterField(
            model_name='campaignnewsmedia',
            name='file',
            field=models.FileField(upload_to=apps.campaigns.models.campaign_news_media_upload_path),
        ),
        migrations.AlterField(
            model_name='campaignteammember',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.campaigns.models.campaign_team_member_profile_picture_upload_path),
        ),
    ]
