# Generated by Django 5.1 on 2024-08-22 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0008_campaignnews_title'),
        ('users', '0002_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignmedia',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='campaignnews',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='campaignnewsmedia',
            name='campaign_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='campaigns.campaignnews'),
        ),
        migrations.AlterField(
            model_name='campaignrating',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='campaignrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='campaignteammember',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='campaigns.campaign'),
        ),
    ]
