# Generated by Django 5.1 on 2024-08-22 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_alter_campaignmedia_campaign_and_more'),
        ('users', '0002_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='campaignvisit',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='campaigns.campaign'),
        ),
        migrations.AlterField(
            model_name='campaignvisit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='users.userprofile'),
        ),
    ]
