# Generated by Django 5.1 on 2024-08-23 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0010_alter_campaign_creator_alter_campaignvisit_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='investment_type',
            field=models.CharField(choices=[('equity', 'Equity'), ('debt', 'Debt'), ('donation', 'Donation')], default='equity', max_length=10),
        ),
    ]
