# Generated by Django 5.1 on 2024-08-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0012_alter_campaign_project_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='company_valuation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='equity_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='repayment_period_months',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
