# Generated by Django 5.1 on 2024-08-29 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0015_campaignfaq'),
        ('users', '0003_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_liked_at', models.DateTimeField(auto_now_add=True)),
                ('last_liked_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Campaign Likes',
                'unique_together': {('user', 'campaign')},
            },
        ),
    ]
