# Generated by Django 5.1 on 2024-08-30 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0017_rename_first_liked_at_campaignlike_liked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='min_investment',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='campaign',
            name='project_passport',
            field=models.FileField(blank=True, null=True, upload_to='campaigns/project_passports/'),
        ),
    ]
