# Generated by Django 5.0.1 on 2024-09-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0018_campaign_min_investment_campaign_project_passport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
