# Generated by Django 5.0.1 on 2024-09-05 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0019_alter_campaign_approval_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('uzs', 'UZS')], default='usd', max_length=10),
        ),
    ]
