# Generated by Django 5.0.1 on 2024-09-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0020_alter_campaign_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='max_goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
