# Generated by Django 5.0.1 on 2024-09-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0021_campaign_max_goal_amount_campaign_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='company_valuation',
        ),
        migrations.AddField(
            model_name='campaign',
            name='extra_info',
            field=models.TextField(blank=True, null=True, verbose_name='Extra Information'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='valuation_cap',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valuation cap (for equity-based campaigns)', max_digits=15, null=True, verbose_name='Valuation cap in USD'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='description',
            field=models.TextField(max_length=255, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='campaigns.campaigntag'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Campaign Title'),
        ),
    ]
