# Generated by Django 5.0.1 on 2024-09-05 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0024_alter_campaign_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
                ('platform', models.CharField(choices=[('telegram', 'Telegram'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('linkedin', 'LinkedIn'), ('website', 'Website')], max_length=10)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='campaigns.campaign')),
            ],
            options={
                'verbose_name_plural': 'Campaign Links',
            },
        ),
    ]
