# Generated by Django 5.0.1 on 2024-09-06 14:05

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0025_campaignlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='pitch',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
