# Generated by Django 5.0.1 on 2024-09-07 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0029_campaignnews_content_alter_campaignnews_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignnews',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Campaign Updates'},
        ),
    ]
