# Generated by Django 5.0.1 on 2024-09-10 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0032_campaignshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignshare',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='campaigns.campaign'),
        ),
    ]
