# Generated by Django 5.0.1 on 2024-09-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0033_alter_campaignshare_campaign'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignshare',
            unique_together=set(),
        ),
    ]
