# Generated by Django 5.0.1 on 2024-09-13 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0034_alter_campaignshare_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaigncategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='campaignfaq',
            options={'ordering': ['order'], 'verbose_name_plural': 'FAQs'},
        ),
        migrations.AlterModelOptions(
            name='campaignlike',
            options={'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='campaignlink',
            options={'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='campaignmedia',
            options={'verbose_name_plural': 'Media'},
        ),
        migrations.AlterModelOptions(
            name='campaignnews',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Updates'},
        ),
        migrations.AlterModelOptions(
            name='campaignnewsmedia',
            options={'verbose_name_plural': 'News Media'},
        ),
        migrations.AlterModelOptions(
            name='campaignrating',
            options={'ordering': ['-rated_at'], 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='campaignshare',
            options={'verbose_name_plural': 'Shares'},
        ),
        migrations.AlterModelOptions(
            name='campaigntag',
            options={'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterModelOptions(
            name='campaignteammember',
            options={'verbose_name_plural': 'Team Members'},
        ),
        migrations.AlterModelOptions(
            name='campaignvisit',
            options={'ordering': ['-visited_at'], 'verbose_name_plural': 'Visits'},
        ),
        migrations.AlterModelOptions(
            name='withdrawalrequest',
            options={'verbose_name': 'Withdrawal Request', 'verbose_name_plural': 'Withdrawal Requests'},
        ),
        migrations.AlterField(
            model_name='campaignlike',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='campaigns.campaign'),
        ),
    ]
