# Generated by Django 5.1 on 2024-08-29 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersavedcampaign',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersavedcampaign',
            name='last_saved_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
