# Generated by Django 5.0.1 on 2024-09-03 11:31

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, validators=[apps.users.models.validate_uzbek_passport_number]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[apps.users.models.validate_uzbek_phone_number]),
        ),
    ]
