# Generated by Django 5.0.1 on 2024-09-09 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_userprofile_passport_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavedcampaign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_campaigns', to='users.userprofile'),
        ),
    ]
