# Generated by Django 5.0.1 on 2024-09-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_usersavedcampaign_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='usersavedcampaign',
            options={'verbose_name_plural': 'Saved Campaigns'},
        ),
    ]
