# Generated by Django 5.0.1 on 2024-09-12 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0034_alter_campaignshare_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_details', models.JSONField()),
                ('modified_details', models.JSONField()),
                ('action', models.CharField(choices=[('requires_admin_review', 'Requires admin review'), ('does_not_require_admin_review', 'Does not require admin review'), ('block_changes', 'Block changes')], max_length=50)),
                ('reason', models.TextField()),
                ('comparison', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_logs', to='campaigns.campaign')),
            ],
        ),
    ]
