# Generated by Django 5.0.1 on 2024-09-13 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationlog',
            options={'verbose_name': 'Moderation Log', 'verbose_name_plural': 'Moderation Logs'},
        ),
    ]
