# Generated by Django 5.1 on 2024-08-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_investment_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='address',
            field=models.CharField(default='Tashkent', max_length=255),
            preserve_default=False,
        ),
    ]
