# Generated by Django 5.0.1 on 2024-09-09 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_alter_investment_user'),
        ('users', '0008_alter_usersavedcampaign_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='users.userprofile'),
        ),
    ]
